# Generated by Django 4.2.9 on 2024-02-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encryptapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="police_station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("phone_number", models.IntegerField(max_length=15)),
                ("email", models.EmailField(max_length=50)),
                ("address", models.TextField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(name="person",),
    ]
