# Generated by Django 4.2.9 on 2024-02-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encryptapp", "0002_police_station_delete_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(max_length=200)),
                ("answer", models.TextField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name="police_station",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
    ]
