# Generated by Django 4.2.9 on 2024-02-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encryptapp", "0003_faq_alter_police_station_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Laws",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sections", models.TextField(max_length=300)),
                ("offence", models.TextField(max_length=200)),
                ("cybersecurity_law", models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Terms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=100)),
                ("description", models.TextField(max_length=400)),
                ("image", models.ImageField(blank=True, upload_to="data")),
            ],
        ),
    ]
