# Generated by Django 4.2.9 on 2024-02-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encryptapp", "0004_laws_terms"),
    ]

    operations = [
        migrations.CreateModel(
            name="Law",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sections", models.TextField(max_length=300)),
                ("offence", models.TextField(max_length=200)),
                ("penalty", models.TextField(max_length=200)),
            ],
        ),
        migrations.RenameModel(old_name="Terms", new_name="Term",),
        migrations.DeleteModel(name="Laws",),
        migrations.AlterField(
            model_name="faq", name="answer", field=models.TextField(max_length=1000),
        ),
    ]
