# Generated by Django 4.2.9 on 2024-02-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encryptapp", "0005_law_rename_terms_term_delete_laws_alter_faq_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="law", name="sections", field=models.TextField(max_length=30),
        ),
    ]
