# Generated by Django 4.2.9 on 2024-02-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encryptapp", "0006_alter_law_sections"),
    ]

    operations = [
        migrations.CreateModel(
            name="Laws",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sections", models.TextField(max_length=30)),
                ("offence", models.TextField(max_length=200)),
                ("penalty", models.TextField(max_length=200)),
                ("cybersecurity_laws", models.TextField(max_length=100)),
            ],
        ),
        migrations.RenameModel(old_name="Term", new_name="Terms",),
        migrations.DeleteModel(name="Law",),
    ]
