# Generated by Django 4.2.9 on 2024-02-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encryptapp", "0007_laws_rename_term_terms_delete_law"),
    ]

    operations = [
        migrations.CreateModel(
            name="cybersecurity_laws",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=100)),
                ("description", models.TextField(max_length=500)),
            ],
        ),
        migrations.RemoveField(model_name="laws", name="cybersecurity_laws",),
    ]
