# Generated by Django 4.2.9 on 2024-02-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encryptapp", "0008_cybersecurity_laws_remove_laws_cybersecurity_laws"),
    ]

    operations = [
        migrations.CreateModel(
            name="userregister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("password", models.TextField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name="cybersecurity_laws",
            name="description",
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name="laws", name="offence", field=models.TextField(max_length=300),
        ),
    ]
