# Generated by Django 4.2.9 on 2024-02-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "encryptapp",
            "0009_userregister_alter_cybersecurity_laws_description_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="contact_us",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("company_name", models.TextField(max_length=100)),
                ("message", models.TextField(max_length=1000)),
            ],
        ),
    ]
