# Generated by Django 4.2.9 on 2024-02-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encryptapp", "0010_contact_us"),
    ]

    operations = [
        migrations.CreateModel(
            name="test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_id", models.TextField(max_length=20)),
                ("test_name", models.CharField(max_length=50)),
            ],
        ),
    ]
