# Generated by Django 4.2.9 on 2024-02-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encryptapp", "0011_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="security_laws",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=100)),
                ("description", models.TextField(max_length=1500)),
            ],
        ),
    ]
