# Generated by Django 4.2.9 on 2024-02-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encryptapp", "0012_security_laws"),
    ]

    operations = [
        migrations.DeleteModel(name="security_laws",),
        migrations.AlterField(
            model_name="test", name="test_id", field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name="test",
            name="test_name",
            field=models.TextField(max_length=1000),
        ),
    ]
