# Generated by Django 4.2.9 on 2024-02-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encryptapp", "0013_delete_security_laws_alter_test_test_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userregister",
            name="address",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="address2",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="city",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="dob",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="gender",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="pin",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="state",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
