# Generated by Django 4.2.9 on 2024-02-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encryptapp", "0014_userregister_address_userregister_address2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="police_station",
            name="image",
            field=models.ImageField(blank=True, upload_to="data"),
        ),
        migrations.AlterField(
            model_name="userregister",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userregister",
            name="dob",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userregister",
            name="gender",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userregister",
            name="pin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userregister",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
