# Generated by Django 4.2.9 on 2024-02-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encryptapp", "0015_police_station_image_alter_userregister_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=200)),
                ("message", models.TextField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(name="test",),
    ]
