# Generated by Django 4.2.9 on 2024-02-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encryptapp", "0016_review_delete_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="userregister",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="data"),
        ),
    ]
