# Generated by Django 4.2.9 on 2024-02-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encryptapp", "0017_userregister_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userregister",
            name="contactno",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="first",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="last",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
