# Generated by Django 4.2.9 on 2024-03-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encryptapp", "0018_userregister_contactno_userregister_first_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="help_support",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=200)),
                ("message", models.TextField(max_length=1000)),
            ],
        ),
    ]
