# Generated by Django 4.2.9 on 2024-03-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encryptapp", "0019_help_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="police_station", name="url", field=models.URLField(blank=True),
        ),
    ]
