# Generated by Django 4.2.9 on 2024-03-20 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("encryptapp", "0020_police_station_url"),
    ]

    operations = [
        migrations.RemoveField(model_name="police_station", name="url",),
    ]
