# Generated by Django 4.2.9 on 2024-04-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encryptapp", "0021_remove_police_station_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="help_support",
            name="username",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="username",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userregister",
            name="contactno",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
